---
all:
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_user: "{{ lookup('env', 'SANDBOX_USER') }}"
    ansible_password: "{{ lookup('env', 'SANDBOX_PASSWORD') }}"
  hosts:
    iosxe_sandbox:
      ansible_host: "{{ lookup('env', 'SANDBOX_HOST') }}"
